### ISSUE TITLE
我有一個問題

### ISSUE THREAD

**Issue by maggiechian926** [hsiaoyt0923/11209_python_school#1]

**Comment by hsiaoyt0923** [comment]
import random
target = random.randint(1,100)
a=1
b=100
count = 0
while (True):
    print("請輸入要猜的數字，在", a , "到",b ,"之間")
    guess  =  int(input())
    if(target == guess):
        print(f'猜到了{count}次:')
        print("恭喜你！已經猜到了")
        break
    elif(target < guess):
        count += 1
        print(f'猜到了{count}次:')
        print("猜錯了豬頭，再小一點")
        *a = guess** 改成 b = guess*
        continue
    elif(target > guess):
        count += 1
        print(f'猜到了{count}次:')
        print("猜錯了咕咕雞，再大一點")
        *b = guess 改成 a = guess*
        continue


這樣應該就可以了，程式碼本身沒問題，提示寫錯才會猜不到。

另外，我把我的答案發佈到ISSUE了，網址如下：

https://github.com/roberthsu2003/__11209python_school__/issues/3

也許可以作為參考。



maggiechiang ***@***.***> 於 2023年9月22日 週五 下午9:17 寫道：
